image: iamapinan/php-nginx-mongo:1.3

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apk --no-cache add openssh rsync
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ssh-add <(echo "$SSH_KEY")
    - rsync -azv --exclude .git  . iotech@$SSH_HOST:/mnt/data/codecamp2019/$CI_PROJECT_NAME
